### ISSUE TITLE
Support an environment variable in the Tmux session that stores the directory where the Tmux session was started

### ISSUE THREAD

**Issue by cloud-j-luna** [Andree37/zsh-navigator#1]
Currently, when initiating a Tmux session through `navigator`, there isn't a straightforward way to capture and store the directory from which the session was started. This feature request proposes introducing support for an environment variable that is automatically set to the initial working directory of the Tmux session.

**Comment by Andree37** [comment]
good feature request, we can now do this by `^h` this will bring you back to your original directory when in tmux mode :) 

https://github.com/Andree37/zsh-navigator/commit/6835b888c275ada4a62f2f072538e9d6d7e46b9f
